#ifndef HEADER_SIMCIV_COMMON_HPP_INCLUDED
#define HEADER_SIMCIV_COMMON_HPP_INCLUDED

#include <fm/types.hpp>

using namespace zn;

#define SIMCIV_DEFAULT_PORT 5551

#endif // HEADER_SIMCIV_COMMON_HPP_INCLUDED


